import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConnectButton, ThirdwebProvider } from "thirdweb/react";
import { client } from "@/lib/client";
import { ContractProvider } from "@/providers/thirdwebHook";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContractProvider>
          <ThirdwebProvider>
            <div className="absolute top-3 right-3">
              <div className="flex justify-center mb-20">
                <ConnectButton
                  client={client}
                  appMetadata={{
                    name: "Example App",
                    url: "https://example.com",
                  }}
                />
              </div>
            </div>
            {children}
          </ThirdwebProvider>
        </ContractProvider>
      </body>
    </html>
  );
}
